version: '3'

services:
  app:
    build:
      context: .
      dockerfile: prod.Dockerfile
    restart: always
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    networks:
            - sail

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    networks:
            - sail
  phpmyadmin:
        image: 'phpmyadmin:latest'
        ports:
            - 8080:80
        networks:
            - sail
        environment:
            - PMA_ARBITRARY=1
networks:
    sail:
        driver: bridge

# Add other services (e.g., Nginx, Redis) as needed
