version: '3'

services:
  app:
    build:
      context: .
      dockerfile: prod.Dockerfile
    restart: always
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=decision_tree_db
      - DB_USERNAME=first_user
      - DB_PASSWORD=first_password
    networks:
            - sail

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'first_password'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'decision_tree_db'
      MYSQL_USER: 'first_user'
      MYSQL_PASSWORD: 'first_password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql_data:/var/lib/mysql  # Named volume for MySQL data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Initialization script
    networks:
            - sail
  phpmyadmin:
        image: 'phpmyadmin:latest'
        ports:
            - 8080:80
        networks:
            - sail
        environment:
            - PMA_ARBITRARY=1
networks:
    sail:
        driver: bridge
volumes:
  mysql_data: